2025-09-17 18:13:39,871 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-17 18:13:39,886 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-17 18:13:39,886 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-17 18:13:39,886 [INFO] werkzeug:  * Restarting with stat
2025-09-17 18:13:40,115 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-17 18:13:40,126 [WARNING] werkzeug:  * Debugger is active!
2025-09-17 18:13:40,127 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-17 18:13:56,863 [INFO] web.app: Ingreso al men√∫ principal
2025-09-17 18:13:56,866 [INFO] werkzeug: 127.0.0.1 - - [17/Sep/2025 18:13:56] "GET / HTTP/1.1" 200 -
2025-09-17 18:13:57,010 [INFO] werkzeug: 127.0.0.1 - - [17/Sep/2025 18:13:57] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-09-17 18:13:59,021 [INFO] web.app: Ingreso a formulario SUNARP
2025-09-17 18:13:59,025 [INFO] werkzeug: 127.0.0.1 - - [17/Sep/2025 18:13:59] "GET /sunarp HTTP/1.1" 200 -
2025-09-17 18:14:03,222 [INFO] sunarp.client: SUNARP - llamada exitosa al endpoint GOficina
2025-09-17 18:14:03,225 [INFO] web.app: Consulta SUNARP exitosa - Listado de oficinas
2025-09-17 18:14:03,234 [INFO] werkzeug: 127.0.0.1 - - [17/Sep/2025 18:14:03] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-17 18:14:15,794 [INFO] sunarp.client: SUNARP - llamada exitosa al endpoint BPJRSocial
2025-09-17 18:14:15,796 [INFO] web.app: Consulta SUNARP exitosa - Persona Jur√≠dica: inveriones jyanel
2025-09-17 18:14:15,798 [INFO] werkzeug: 127.0.0.1 - - [17/Sep/2025 18:14:15] "POST /sunarp/pj HTTP/1.1" 200 -
2025-09-18 09:31:53,533 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 09:31:53,647 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-18 09:31:53,648 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-18 09:31:53,649 [INFO] werkzeug:  * Restarting with stat
2025-09-18 09:31:53,948 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 09:31:53,959 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 09:31:53,973 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 09:32:14,893 [INFO] web.app: Ingreso al men√∫ principal
2025-09-18 09:32:14,913 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 09:32:14] "GET / HTTP/1.1" 200 -
2025-09-18 09:32:15,065 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 09:32:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-09-18 09:32:16,316 [INFO] web.app: Ingreso a formulario RENIEC
2025-09-18 09:32:16,333 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 09:32:16] "GET /reniec HTTP/1.1" 200 -
2025-09-18 09:32:22,045 [INFO] reniec.client: RENIEC - consulta exitosa para DNI 44494551
2025-09-18 09:32:22,055 [INFO] web.app: Consulta RENIEC exitosa para DNI: 44494551
2025-09-18 09:32:22,072 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 09:32:22] "POST /reniec HTTP/1.1" 200 -
2025-09-18 09:32:24,321 [INFO] web.app: Ingreso al men√∫ principal
2025-09-18 09:32:24,322 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 09:32:24] "GET / HTTP/1.1" 200 -
2025-09-18 09:32:25,377 [INFO] web.app: Ingreso a formulario SUNARP
2025-09-18 09:32:25,394 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 09:32:25] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 09:32:39,387 [ERROR] sunarp.client: SUNARP - error en endpoint VDRPVExtra: 500 Server Error: Internal Server Error for url: https://ws2.pide.gob.pe/Rest/SUNARP/VDRPVExtra?out=json
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\client.py", line 24, in _post
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ws2.pide.gob.pe/Rest/SUNARP/VDRPVExtra?out=json
2025-09-18 09:32:39,443 [ERROR] web.app: Error en consulta SUNARP Placa CFL523: 500 Server Error: Internal Server Error for url: https://ws2.pide.gob.pe/Rest/SUNARP/VDRPVExtra?out=json
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 70, in consulta_placa
    resp = client.consulta_placa(zona, oficina, placa)
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\client.py", line 34, in consulta_placa
    return self._post("VDRPVExtra", {"zona": zona, "oficina": oficina, "placa": placa})
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\client.py", line 24, in _post
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ws2.pide.gob.pe/Rest/SUNARP/VDRPVExtra?out=json
2025-09-18 09:32:39,448 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 09:32:39] "POST /sunarp/placa HTTP/1.1" 200 -
2025-09-18 12:12:22,560 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:12:22,626 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-18 12:12:22,626 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-18 12:12:22,628 [INFO] werkzeug:  * Restarting with stat
2025-09-18 12:12:22,822 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:12:22,831 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 12:12:22,836 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 12:12:26,732 [INFO] web.app: Ingreso al men√∫ principal
2025-09-18 12:12:26,747 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:12:26] "GET / HTTP/1.1" 200 -
2025-09-18 12:12:26,926 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:12:26] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-09-18 12:13:02,118 [INFO] web.app: Ingreso a formulario SUNARP
2025-09-18 12:13:02,134 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:13:02] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 12:13:14,111 [INFO] sunarp.client: SUNARP - llamada exitosa al endpoint VDRPVExtra
2025-09-18 12:13:14,115 [INFO] web.app: Consulta SUNARP exitosa - Placa: cfl523, Zona: 01, Oficina: 01
2025-09-18 12:13:14,151 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:13:14] "POST /sunarp/placa HTTP/1.1" 200 -
2025-09-18 12:13:20,699 [INFO] web.app: Ingreso al men√∫ principal
2025-09-18 12:13:20,700 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:13:20] "GET / HTTP/1.1" 200 -
2025-09-18 12:13:21,653 [INFO] web.app: Ingreso a formulario SUNARP
2025-09-18 12:13:21,654 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:13:21] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 12:13:29,624 [ERROR] sunarp.client: SUNARP - error en endpoint VDRPVExtra: 500 Server Error: Internal Server Error for url: https://ws2.pide.gob.pe/Rest/SUNARP/VDRPVExtra?out=json
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\client.py", line 24, in _post
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ws2.pide.gob.pe/Rest/SUNARP/VDRPVExtra?out=json
2025-09-18 12:13:29,643 [ERROR] web.app: Error en consulta SUNARP Placa cfl523: 500 Server Error: Internal Server Error for url: https://ws2.pide.gob.pe/Rest/SUNARP/VDRPVExtra?out=json
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 70, in consulta_placa
    resp = client.consulta_placa(zona, oficina, placa)
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\client.py", line 34, in consulta_placa
    return self._post("VDRPVExtra", {"zona": zona, "oficina": oficina, "placa": placa})
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\client.py", line 24, in _post
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://ws2.pide.gob.pe/Rest/SUNARP/VDRPVExtra?out=json
2025-09-18 12:13:29,651 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:13:29] "POST /sunarp/placa HTTP/1.1" 200 -
2025-09-18 12:13:39,172 [INFO] sunarp.client: SUNARP - llamada exitosa al endpoint GOficina
2025-09-18 12:13:39,177 [INFO] web.app: Consulta SUNARP exitosa - Listado de oficinas
2025-09-18 12:13:39,182 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:13:39] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-18 12:45:23,279 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\client.py', reloading
2025-09-18 12:45:23,317 [INFO] werkzeug:  * Restarting with stat
2025-09-18 12:45:23,543 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:45:23,553 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 12:45:23,555 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 12:46:18,013 [INFO] web.app: Ingreso al men√∫ principal
2025-09-18 12:46:18,015 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:46:18] "GET / HTTP/1.1" 200 -
2025-09-18 12:46:18,900 [INFO] web.app: Ingreso a formulario SUNARP
2025-09-18 12:46:18,902 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:46:18] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 12:46:20,652 [INFO] sunarp.client: SUNARP - llamada exitosa al endpoint GOficina
2025-09-18 12:46:20,655 [INFO] web.app: Consulta SUNARP exitosa - Listado de oficinas
2025-09-18 12:46:20,667 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:46:20] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-18 12:46:44,020 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:46:44,034 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-18 12:46:44,034 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-18 12:46:44,035 [INFO] werkzeug:  * Restarting with stat
2025-09-18 12:46:44,229 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:46:44,237 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 12:46:44,239 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 12:46:51,058 [INFO] web.app: Ingreso al men√∫ principal
2025-09-18 12:46:51,061 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:46:51] "GET / HTTP/1.1" 200 -
2025-09-18 12:46:52,100 [INFO] web.app: Ingreso a formulario SUNARP
2025-09-18 12:46:52,103 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:46:52] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 12:46:54,134 [INFO] sunarp.client: SUNARP - llamada exitosa al endpoint GOficina
2025-09-18 12:46:54,135 [INFO] web.app: Consulta SUNARP exitosa - Listado de oficinas
2025-09-18 12:46:54,139 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:46:54] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-18 12:50:17,960 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\client.py', reloading
2025-09-18 12:50:17,988 [INFO] werkzeug:  * Restarting with stat
2025-09-18 12:50:18,205 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:50:18,217 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 12:50:18,219 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 12:50:54,327 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\client.py', reloading
2025-09-18 12:50:54,353 [INFO] werkzeug:  * Restarting with stat
2025-09-18 12:51:22,371 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:51:22,388 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-18 12:51:22,388 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-18 12:51:22,389 [INFO] werkzeug:  * Restarting with stat
2025-09-18 12:51:22,571 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:51:22,579 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 12:51:22,581 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 12:53:18,938 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\client.py', reloading
2025-09-18 12:53:18,966 [INFO] werkzeug:  * Restarting with stat
2025-09-18 12:53:19,175 [INFO] web.app: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 12:53:19,185 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 12:53:19,187 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 12:54:29,795 [INFO] web.app: Ingreso al men√∫ principal
2025-09-18 12:54:29,796 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:54:29] "GET / HTTP/1.1" 200 -
2025-09-18 12:54:30,509 [INFO] web.app: Ingreso a formulario SUNARP
2025-09-18 12:54:30,511 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:54:30] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 12:54:32,603 [INFO] sunarp.client: SUNARP - POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-18 12:54:32,604 [INFO] sunarp.client: Payload enviado: {'PIDE': {'usuario': '20494443466-SAT-H', 'clave': 'SunarpSegdi'}}
2025-09-18 12:54:32,604 [INFO] sunarp.client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-18 12:54:32,606 [INFO] web.app: Consulta SUNARP exitosa - Listado de oficinas
2025-09-18 12:54:32,611 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:54:32] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-18 12:54:34,093 [INFO] web.app: Ingreso al men√∫ principal
2025-09-18 12:54:34,093 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 12:54:34] "GET / HTTP/1.1" 200 -
2025-09-18 14:45:56,752 [INFO] web.app: Ingreso a formulario SUNARP
2025-09-18 14:45:56,752 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 14:45:56] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 14:45:59,317 [INFO] sunarp.client: SUNARP - POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-18 14:45:59,317 [INFO] sunarp.client: Payload enviado: {'PIDE': {'usuario': '20494443466-SAT-H', 'clave': 'SunarpSegdi'}}
2025-09-18 14:45:59,317 [INFO] sunarp.client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-18 14:45:59,318 [INFO] web.app: Consulta SUNARP exitosa - Listado de oficinas
2025-09-18 14:45:59,319 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 14:45:59] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-18 15:02:25,195 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\client.py', reloading
2025-09-18 15:02:25,232 [INFO] werkzeug:  * Restarting with stat
2025-09-18 16:14:22,424 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 16:14:22,438 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-18 16:14:22,439 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-18 16:14:22,439 [INFO] werkzeug:  * Restarting with stat
2025-09-18 16:14:22,682 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 16:14:22,691 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 16:14:22,692 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 16:17:38,662 [INFO] __main__: Ingreso al men√∫ principal
2025-09-18 16:17:38,676 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:17:38] "GET / HTTP/1.1" 200 -
2025-09-18 16:17:39,702 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-18 16:17:39,706 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:17:39] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 16:17:46,191 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:17:46] "[35m[1mPOST /sunarp/pj HTTP/1.1[0m" 500 -
2025-09-18 16:17:46,266 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:17:46] "GET /sunarp/pj?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-09-18 16:17:46,533 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:17:46] "GET /sunarp/pj?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-09-18 16:17:46,875 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:17:46] "GET /sunarp/pj?__debugger__=yes&cmd=resource&f=console.png&s=Q7rmOhsqwLuqvjzic0mO HTTP/1.1" 200 -
2025-09-18 16:17:47,122 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:17:47] "GET /sunarp/pj?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-09-18 16:18:01,236 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:18:01] "[35m[1mGET /sunarp/oficinas HTTP/1.1[0m" 500 -
2025-09-18 16:18:01,259 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:18:01] "[36mGET /sunarp/oficinas?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2025-09-18 16:18:01,565 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:18:01] "[36mGET /sunarp/oficinas?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2025-09-18 16:18:01,905 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:18:01] "GET /sunarp/oficinas?__debugger__=yes&cmd=resource&f=console.png&s=Q7rmOhsqwLuqvjzic0mO HTTP/1.1" 200 -
2025-09-18 16:26:52,150 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\sunarp_client.py', reloading
2025-09-18 16:26:52,183 [INFO] werkzeug:  * Restarting with stat
2025-09-18 16:26:52,449 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 16:26:52,457 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 16:26:52,459 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 16:30:24,967 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\sunarp_client.py', reloading
2025-09-18 16:30:25,002 [INFO] werkzeug:  * Restarting with stat
2025-09-18 16:30:25,262 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-18 16:30:25,270 [WARNING] werkzeug:  * Debugger is active!
2025-09-18 16:30:25,272 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-18 16:30:51,672 [INFO] __main__: Ingreso al men√∫ principal
2025-09-18 16:30:51,676 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:30:51] "GET / HTTP/1.1" 200 -
2025-09-18 16:30:52,919 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-18 16:30:52,921 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:30:52] "GET /sunarp HTTP/1.1" 200 -
2025-09-18 16:30:55,439 [INFO] pide_client.sunarp.sunarp_client: SUNARP REST - POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-18 16:30:55,440 [INFO] pide_client.sunarp.sunarp_client: Payload enviado: {"PIDE": {"usuario": "20494443466-SAT-H", "clave": "SunarpSegdi"}}
2025-09-18 16:30:55,441 [INFO] pide_client.sunarp.sunarp_client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-18 16:30:55,444 [INFO] __main__: Consulta SUNARP exitosa - Listado de oficinas
2025-09-18 16:30:55,450 [INFO] werkzeug: 127.0.0.1 - - [18/Sep/2025 16:30:55] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-19 11:30:39,518 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 11:30:39,576 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-19 11:30:39,576 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-19 11:30:39,578 [INFO] werkzeug:  * Restarting with stat
2025-09-19 11:30:39,813 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 11:30:39,822 [WARNING] werkzeug:  * Debugger is active!
2025-09-19 11:30:39,826 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-19 11:30:53,947 [INFO] __main__: Ingreso al men√∫ principal
2025-09-19 11:30:53,966 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:30:53] "GET / HTTP/1.1" 200 -
2025-09-19 11:30:56,104 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:30:56] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-09-19 11:30:56,993 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-19 11:30:57,014 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:30:57] "GET /sunarp HTTP/1.1" 200 -
2025-09-19 11:31:10,103 [INFO] pide_client.sunarp.sunarp_client: SUNARP REST - POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-19 11:31:10,104 [INFO] pide_client.sunarp.sunarp_client: Payload enviado: {"PIDE": {"usuario": "20494443466-SAT-H", "clave": "SunarpSegdi"}}
2025-09-19 11:31:10,104 [INFO] pide_client.sunarp.sunarp_client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-19 11:31:10,115 [INFO] __main__: Consulta SUNARP exitosa - Listado de oficinas
2025-09-19 11:31:10,455 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:31:10] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-19 11:31:14,569 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-19 11:31:14,570 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:31:14] "GET /sunarp HTTP/1.1" 200 -
2025-09-19 11:31:24,620 [INFO] pide_client.sunarp.sunarp_client: SUNARP REST - POST https://ws2.pide.gob.pe/Rest/SUNARP/BPJRSocial?out=json
2025-09-19 11:31:24,621 [INFO] pide_client.sunarp.sunarp_client: Payload enviado: {"PIDE": {"usuario": "20494443466-SAT-H", "clave": "SunarpSegdi", "razonSocial": "inversiones jyanel"}}
2025-09-19 11:31:24,621 [INFO] pide_client.sunarp.sunarp_client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-19 11:31:24,623 [INFO] __main__: Consulta SUNARP exitosa - Persona Jur√≠dica: inversiones jyanel
2025-09-19 11:31:24,624 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:31:24] "POST /sunarp/pj HTTP/1.1" 200 -
2025-09-19 11:31:27,465 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-19 11:31:27,466 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:31:27] "GET /sunarp HTTP/1.1" 200 -
2025-09-19 11:31:40,393 [INFO] pide_client.sunarp.sunarp_client: Inicializando cliente SOAP SUNARP...
2025-09-19 11:31:42,724 [ERROR] pide_client.sunarp.sunarp_client: SUNARP SOAP - error en m√©todo verDetalleRPVExtra: Invalid XML content received (Document is empty, line 1, column 1)
Traceback (most recent call last):
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\loader.py", line 50, in parse_xml
    elementtree = fromstring(content, parser=parser, base_url=base_url)
  File "src/lxml/etree.pyx", line 3428, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 2059, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1937, in lxml.etree._parseDoc_bytes
  File "src/lxml/parser.pxi", line 1191, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 647, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 765, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 689, in lxml.etree._raiseParseError
  File "https://ws2.pide.gob.pe/services/SUNARPService?wsdl", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 64, in _soap_call
    client = self._get_soap_client()
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 59, in _get_soap_client
    self.soap = Client(self.WSDL_URL)
                ~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\client.py", line 76, in __init__
    self.wsdl = Document(wsdl, self.transport, settings=self.settings)
                ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\wsdl\wsdl.py", line 86, in __init__
    self.load(location)
    ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\wsdl\wsdl.py", line 89, in load
    document = self._get_xml_document(location)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\wsdl\wsdl.py", line 149, in _get_xml_document
    return load_external(
        location, self.transport, self.location, settings=self.settings
    )
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\loader.py", line 90, in load_external
    return parse_xml(content, transport, base_url, settings=settings)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\loader.py", line 66, in parse_xml
    raise XMLSyntaxError(
        "Invalid XML content received (%s)" % exc.msg, content=content
    )
zeep.exceptions.XMLSyntaxError: Invalid XML content received (Document is empty, line 1, column 1)
2025-09-19 11:31:43,252 [ERROR] __main__: Error en consulta SUNARP Placa cfl523: Invalid XML content received (Document is empty, line 1, column 1)
Traceback (most recent call last):
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\loader.py", line 50, in parse_xml
    elementtree = fromstring(content, parser=parser, base_url=base_url)
  File "src/lxml/etree.pyx", line 3428, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 2059, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1937, in lxml.etree._parseDoc_bytes
  File "src/lxml/parser.pxi", line 1191, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 647, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 765, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 689, in lxml.etree._raiseParseError
  File "https://ws2.pide.gob.pe/services/SUNARPService?wsdl", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 70, in consulta_placa
    resp = client.consulta_placa(zona, oficina, placa)
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 88, in consulta_placa
    return self._soap_call("verDetalleRPVExtra", zona=zona, oficina=oficina, placa=placa)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 64, in _soap_call
    client = self._get_soap_client()
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 59, in _get_soap_client
    self.soap = Client(self.WSDL_URL)
                ~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\client.py", line 76, in __init__
    self.wsdl = Document(wsdl, self.transport, settings=self.settings)
                ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\wsdl\wsdl.py", line 86, in __init__
    self.load(location)
    ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\wsdl\wsdl.py", line 89, in load
    document = self._get_xml_document(location)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\wsdl\wsdl.py", line 149, in _get_xml_document
    return load_external(
        location, self.transport, self.location, settings=self.settings
    )
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\loader.py", line 90, in load_external
    return parse_xml(content, transport, base_url, settings=settings)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\zeep\loader.py", line 66, in parse_xml
    raise XMLSyntaxError(
        "Invalid XML content received (%s)" % exc.msg, content=content
    )
zeep.exceptions.XMLSyntaxError: Invalid XML content received (Document is empty, line 1, column 1)
2025-09-19 11:31:43,261 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:31:43] "POST /sunarp/placa HTTP/1.1" 200 -
2025-09-19 11:34:28,985 [INFO] pide_client.sunarp.sunarp_client: SUNARP REST - POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-19 11:34:28,987 [INFO] pide_client.sunarp.sunarp_client: Payload enviado: {"PIDE": {"usuario": "20494443466-SAT-H", "clave": "SunarpSegdi"}}
2025-09-19 11:34:28,989 [INFO] pide_client.sunarp.sunarp_client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-19 11:34:29,000 [INFO] __main__: Consulta SUNARP exitosa - Listado de oficinas
2025-09-19 11:34:29,005 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:34:29] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-19 11:47:30,960 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\sunarp_client.py', reloading
2025-09-19 11:47:31,019 [INFO] werkzeug:  * Restarting with stat
2025-09-19 11:55:28,245 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 11:55:28,260 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-19 11:55:28,260 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-19 11:55:28,261 [INFO] werkzeug:  * Restarting with stat
2025-09-19 11:55:28,502 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 11:55:28,512 [WARNING] werkzeug:  * Debugger is active!
2025-09-19 11:55:28,514 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-19 11:55:35,644 [INFO] __main__: Ingreso al men√∫ principal
2025-09-19 11:55:35,645 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:55:35] "GET / HTTP/1.1" 200 -
2025-09-19 11:55:37,029 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-19 11:55:37,033 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:55:37] "GET /sunarp HTTP/1.1" 200 -
2025-09-19 11:55:44,947 [INFO] pide_client.sunarp.sunarp_client: SUNARP REST POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-19 11:55:44,948 [INFO] pide_client.sunarp.sunarp_client: Payload enviado: {"PIDE": {"usuario": "20494443466-SAT-H", "clave": "SunarpSegdi"}}
2025-09-19 11:55:44,949 [INFO] pide_client.sunarp.sunarp_client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-19 11:55:44,953 [ERROR] pide_client.sunarp.sunarp_client: SUNARP REST - error en GOficina: Usuario o password incorrectos en SUNARP
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 72, in _rest_request
    self._check_response_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 122, in _check_response_errors
    raise SunarpAuthError("Usuario o password incorrectos en SUNARP")
pide_client.sunarp.sunarp_client.SunarpAuthError: Usuario o password incorrectos en SUNARP
2025-09-19 11:55:44,963 [ERROR] __main__: Error en consulta SUNARP Listar Oficinas: Usuario o password incorrectos en SUNARP
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 113, in listar_oficinas
    resp = client.listar_oficinas()
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 133, in listar_oficinas
    return self._rest_request("GOficina")
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 72, in _rest_request
    self._check_response_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 122, in _check_response_errors
    raise SunarpAuthError("Usuario o password incorrectos en SUNARP")
pide_client.sunarp.sunarp_client.SunarpAuthError: Usuario o password incorrectos en SUNARP
2025-09-19 11:55:44,975 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 11:55:44] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-19 12:09:36,506 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 12:09:36,525 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-19 12:09:36,525 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-19 12:09:36,526 [INFO] werkzeug:  * Restarting with stat
2025-09-19 12:09:36,820 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 12:09:36,830 [WARNING] werkzeug:  * Debugger is active!
2025-09-19 12:09:36,832 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-19 12:09:43,766 [INFO] __main__: Ingreso al men√∫ principal
2025-09-19 12:09:43,768 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:09:43] "GET / HTTP/1.1" 200 -
2025-09-19 12:09:44,657 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-19 12:09:44,661 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:09:44] "GET /sunarp HTTP/1.1" 200 -
2025-09-19 12:09:47,248 [INFO] pide_client.sunarp.sunarp_client: SUNARP REST POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-19 12:09:47,249 [INFO] pide_client.sunarp.sunarp_client: Payload enviado: {"PIDE": {"usuario": "20494443466-SAT-H", "clave": "SunarpSegdi"}}
2025-09-19 12:09:47,250 [INFO] pide_client.sunarp.sunarp_client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-19 12:09:47,251 [ERROR] pide_client.sunarp.sunarp_client: SUNARP REST - error en GOficina: Usuario o password incorrectos en SUNARP
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 72, in _rest_request
    self._check_response_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 122, in _check_response_errors
    raise SunarpAuthError("Usuario o password incorrectos en SUNARP")
pide_client.sunarp.sunarp_client.SunarpAuthError: Usuario o password incorrectos en SUNARP
2025-09-19 12:09:47,254 [ERROR] __main__: Error en consulta SUNARP Listar Oficinas: Usuario o password incorrectos en SUNARP
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 113, in listar_oficinas
    resp = client.listar_oficinas()
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 133, in listar_oficinas
    return self._rest_request("GOficina")
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 72, in _rest_request
    self._check_response_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 122, in _check_response_errors
    raise SunarpAuthError("Usuario o password incorrectos en SUNARP")
pide_client.sunarp.sunarp_client.SunarpAuthError: Usuario o password incorrectos en SUNARP
2025-09-19 12:09:47,263 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:09:47] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-19 12:11:58,013 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\test_sunarp.py', reloading
2025-09-19 12:11:58,095 [INFO] werkzeug:  * Restarting with stat
2025-09-19 12:11:58,337 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 12:11:58,347 [WARNING] werkzeug:  * Debugger is active!
2025-09-19 12:11:58,348 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-19 12:14:37,860 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 12:14:37,875 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-19 12:14:37,875 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-19 12:14:37,876 [INFO] werkzeug:  * Restarting with stat
2025-09-19 12:14:38,103 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 12:14:38,111 [WARNING] werkzeug:  * Debugger is active!
2025-09-19 12:14:38,113 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-19 12:14:42,685 [INFO] __main__: Ingreso al men√∫ principal
2025-09-19 12:14:42,686 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:14:42] "GET / HTTP/1.1" 200 -
2025-09-19 12:14:43,633 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-19 12:14:43,635 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:14:43] "GET /sunarp HTTP/1.1" 200 -
2025-09-19 12:14:45,907 [INFO] pide_client.sunarp.sunarp_client: SUNARP REST POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-19 12:14:45,908 [INFO] pide_client.sunarp.sunarp_client: Payload enviado: {"PIDE": {"usuario": "20494443466-SAT-H", "clave": "SunarpSegdi"}}
2025-09-19 12:14:45,910 [INFO] pide_client.sunarp.sunarp_client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-19 12:14:45,913 [ERROR] pide_client.sunarp.sunarp_client: SUNARP REST - error en GOficina: Usuario o password incorrectos en SUNARP
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 72, in _rest_request
    self._check_response_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 122, in _check_response_errors
    raise SunarpAuthError("Usuario o password incorrectos en SUNARP")
pide_client.sunarp.sunarp_client.SunarpAuthError: Usuario o password incorrectos en SUNARP
2025-09-19 12:14:45,919 [ERROR] __main__: Error en consulta SUNARP Listar Oficinas: Usuario o password incorrectos en SUNARP
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 113, in listar_oficinas
    resp = client.listar_oficinas()
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 133, in listar_oficinas
    return self._rest_request("GOficina")
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 72, in _rest_request
    self._check_response_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 122, in _check_response_errors
    raise SunarpAuthError("Usuario o password incorrectos en SUNARP")
pide_client.sunarp.sunarp_client.SunarpAuthError: Usuario o password incorrectos en SUNARP
2025-09-19 12:14:45,925 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:14:45] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-19 12:15:00,032 [INFO] pide_client.sunarp.sunarp_client: Inicializando cliente SOAP SUNARP...
2025-09-19 12:15:02,021 [INFO] pide_client.sunarp.sunarp_client: SUNARP SOAP - Llamando verDetalleRPVExtra con {'zona': '01', 'oficina': '01', 'placa': 'CFL523'}
2025-09-19 12:15:02,613 [INFO] __main__: Consulta SUNARP exitosa - Placa: CFL523, Zona: 01, Oficina: 01
2025-09-19 12:15:02,637 [ERROR] __main__: Error en consulta SUNARP Placa CFL523: Object of type respuestaVehiculoExtraBean is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 72, in consulta_placa
    return render_template("result_sunarp.html", tipo="placa", data=resp)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\templates\result_sunarp.html", line 13, in top-level template code
    <pre class="bg-light p-3 border rounded">{{ data | tojson(indent=2) }}</pre>
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
    ~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type respuestaVehiculoExtraBean is not JSON serializable
2025-09-19 12:15:02,752 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:15:02] "POST /sunarp/placa HTTP/1.1" 200 -
2025-09-19 12:15:13,258 [INFO] pide_client.sunarp.sunarp_client: SUNARP REST POST https://ws2.pide.gob.pe/Rest/SUNARP/GOficina?out=json
2025-09-19 12:15:13,259 [INFO] pide_client.sunarp.sunarp_client: Payload enviado: {"PIDE": {"usuario": "20494443466-SAT-H", "clave": "SunarpSegdi"}}
2025-09-19 12:15:13,260 [INFO] pide_client.sunarp.sunarp_client: Respuesta 200: {"Respuesta":{"Error":"Su usuario o password estan errados"}}
2025-09-19 12:15:13,261 [ERROR] pide_client.sunarp.sunarp_client: SUNARP REST - error en GOficina: Usuario o password incorrectos en SUNARP
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 72, in _rest_request
    self._check_response_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 122, in _check_response_errors
    raise SunarpAuthError("Usuario o password incorrectos en SUNARP")
pide_client.sunarp.sunarp_client.SunarpAuthError: Usuario o password incorrectos en SUNARP
2025-09-19 12:15:13,265 [ERROR] __main__: Error en consulta SUNARP Listar Oficinas: Usuario o password incorrectos en SUNARP
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 113, in listar_oficinas
    resp = client.listar_oficinas()
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 133, in listar_oficinas
    return self._rest_request("GOficina")
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 72, in _rest_request
    self._check_response_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\sunarp\sunarp_client.py", line 122, in _check_response_errors
    raise SunarpAuthError("Usuario o password incorrectos en SUNARP")
pide_client.sunarp.sunarp_client.SunarpAuthError: Usuario o password incorrectos en SUNARP
2025-09-19 12:15:13,283 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:15:13] "GET /sunarp/oficinas HTTP/1.1" 200 -
2025-09-19 12:19:50,940 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\test_login_sunarp.py', reloading
2025-09-19 12:19:51,034 [INFO] werkzeug:  * Restarting with stat
2025-09-19 12:19:51,896 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 12:19:51,976 [WARNING] werkzeug:  * Debugger is active!
2025-09-19 12:19:51,978 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-19 12:53:07,772 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 12:53:07,786 [INFO] werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-09-19 12:53:07,786 [INFO] werkzeug: [33mPress CTRL+C to quit[0m
2025-09-19 12:53:07,787 [INFO] werkzeug:  * Restarting with stat
2025-09-19 12:53:08,015 [INFO] __main__: Iniciando aplicaci√≥n Flask en puerto 5000
2025-09-19 12:53:08,023 [WARNING] werkzeug:  * Debugger is active!
2025-09-19 12:53:08,025 [INFO] werkzeug:  * Debugger PIN: 605-583-089
2025-09-19 12:53:13,692 [INFO] __main__: Ingreso al men√∫ principal
2025-09-19 12:53:13,695 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:53:13] "GET / HTTP/1.1" 200 -
2025-09-19 12:53:14,649 [INFO] __main__: Ingreso a formulario SUNARP
2025-09-19 12:53:14,652 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:53:14] "GET /sunarp HTTP/1.1" 200 -
2025-09-19 12:53:28,682 [INFO] pide_client.sunarp.sunarp_client: Inicializando cliente SOAP SUNARP...
2025-09-19 12:53:30,961 [INFO] pide_client.sunarp.sunarp_client: SUNARP SOAP - Llamando verDetalleRPVExtra con {'zona': '01', 'oficina': '01', 'placa': 'CFL523'}
2025-09-19 12:53:31,487 [INFO] __main__: Consulta SUNARP exitosa - Placa: CFL523, Zona: 01, Oficina: 01
2025-09-19 12:53:31,536 [ERROR] __main__: Error en consulta SUNARP Placa CFL523: Object of type respuestaVehiculoExtraBean is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\app.py", line 72, in consulta_placa
    return render_template("result_sunarp.html", tipo="placa", data=resp)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\UDESA01\Documents\Proyectos Python\pide_client\web\templates\result_sunarp.html", line 13, in top-level template code
    <pre class="bg-light p-3 border rounded">{{ data | tojson(indent=2) }}</pre>
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\jinja2\utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
    ~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\json\provider.py", line 180, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\UDESA01\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\json\provider.py", line 120, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type respuestaVehiculoExtraBean is not JSON serializable
2025-09-19 12:53:31,648 [INFO] werkzeug: 127.0.0.1 - - [19/Sep/2025 12:53:31] "POST /sunarp/placa HTTP/1.1" 200 -
2025-09-19 12:59:54,109 [INFO] werkzeug:  * Detected change in 'C:\\Users\\UDESA01\\Documents\\Proyectos Python\\pide_client\\sunarp\\sunarp_client.py', reloading
2025-09-19 12:59:54,143 [INFO] werkzeug:  * Restarting with stat
